import test from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { cohortRequestBody, validateCohortEndpoint, cohortReservation, cohortAccountedCost, firstDraftComparison, candidateIdentityFailures, claimCohortPlan, summarizeCohort, type CohortPlan } from "../scripts/candidate-cohort-study.ts";
import { resolveGraphConfig } from "../src/disposition/graph-config.ts";
import { GRAPH_OUTPUT_LIMITS, GRAPH_VERSION, draftSchema } from "../src/disposition/clinical-graph.ts";
import { sha256 } from "../src/evidence/rag/model.ts";
import type { DispositionRun } from "../src/disposition/contract.ts";

// This file tests the historical v22 cohort contract, not the current runtime.
const config=resolveGraphConfig(),reservation=cohortReservation(config,"evidence-graph/v22");
const draft=draftSchema.parse({disposition:"SELF_CARE",reviewPriority:null,workType:null,transportIntent:null,reason:"Synthetic routing rationale for a software test.",patientMessage:"Synthetic self-care response for software testing only.",differential:["Synthetic consideration"],redFlags:[{concern:"Synthetic finding",status:"unknown",quote:""}],vitalSigns:"Measurements unknown.",questions:[],citations:[],evidenceLimitations:"Synthetic software test, not clinical evidence."});
function run():DispositionRun{return {runId:"synthetic-run",message:"Synthetic message",inputHash:sha256("Synthetic message"),promptHash:"a".repeat(64),status:"complete",answer:{...draft,evidence:[]},durationMs:12,completedAt:"2026-09-14T12:00:00Z",checks:[],modelCalls:1,agents:[{role:"disposition",model:config.models.disposition,modelCalls:1,output:draft,failure:null,usage:{inputTokens:100,outputTokens:100}}],graph:{version:"evidence-graph/v22",mode:"hybrid",retrieval:[],judge:null}} as unknown as DispositionRun;}
test("HTTP body never transmits reference or original labels",()=>{assert.deepEqual(cohortRequestBody("patient text"),{message:"patient text",syntheticOnly:true});assert.deepEqual(Object.keys(cohortRequestBody("patient text")),["message","syntheticOnly"]);});
test("only local candidate endpoint is allowed",()=>{assert.equal(validateCohortEndpoint("http://localhost:4120/api/candidate").pathname,"/api/candidate");for(const bad of ["https://example.com/api/candidate","http://localhost:4120/api/disposition","http://user@localhost:4120/api/candidate","http://localhost:4120/api/candidate?label=EMERGENCY_NOW"])assert.throws(()=>validateCohortEndpoint(bad));});
test("historical reservation includes nine calls; unregistered current versions remain refused",()=>{assert.equal(reservation.maximumCalls,9);assert.equal(reservation.calls.filter(c=>c.role==="judge").reduce((n,c)=>n+c.count,0),4);assert.equal(reservation.calls.filter(c=>c.outputTokenBound===GRAPH_OUTPUT_LIMITS.truncatedJudgeRecovery).reduce((n,c)=>n+c.count,0),2);assert.ok(reservation.perRunUSD>1);assert.ok(reservation.perRunUSD<55);assert.throws(()=>cohortReservation({...config,safetyStyle:"compact"},"evidence-graph/v22"),/FROZEN_FULL/);if(!["evidence-graph/v22","evidence-graph/v23"].includes(GRAPH_VERSION))assert.throws(()=>cohortReservation(config),/UNREGISTERED_COHORT_GRAPH_VERSION/);});
test("unknown or incomplete usage retains a full reservation, known usage includes contingency and embeddings",()=>{assert.equal(cohortAccountedCost(null,reservation).accountedUSD,reservation.perRunUSD);const r=run();assert.equal(cohortAccountedCost(r,reservation).unknownUsage,false);assert.ok(cohortAccountedCost(r,reservation).accountedUSD>cohortAccountedCost(r,reservation).estimatedUSD!);r.modelCalls=2;assert.equal(cohortAccountedCost(r,reservation).unknownUsage,true);});
test("non-finite provider usage cannot bypass the budget",()=>{const r=run();r.agents![0].usage.inputTokens=NaN;assert.equal(cohortAccountedCost(r,reservation).unknownUsage,true);assert.equal(cohortAccountedCost(r,reservation).accountedUSD,reservation.perRunUSD);});
test("first provider failure cannot be replaced by a later successful draft",()=>{const r=run();r.agents!.unshift({...r.agents![0],output:null,failure:"PROVIDER_FAILED"});const comparison=firstDraftComparison(r,["SELF_CARE"]);assert.equal(comparison.firstRoute,null);assert.equal(comparison.firstProviderAttemptFailure,"PROVIDER_FAILED");assert.equal(comparison.finalReferenceAgreement,true);assert.equal(comparison.referenceDisagreementCorrected,false);});
test("parseable partial output from a failed first provider attempt still fails",()=>{const r=run();r.agents![0].failure="INCOMPLETE_MODEL_STREAM";const result=firstDraftComparison(r,["SELF_CARE"]);assert.equal(result.firstProviderDraftSchemaValid,true);assert.equal(result.firstProviderDraftValid,false);assert.equal(result.firstRoute,null);assert.equal(result.firstReferenceAgreement,null);});
test("withheld matching draft is not called a clinical false rejection; qualified DVT never gets an invented target",()=>{const r=run();r.status="review_required";r.answer=null;const comparison=firstDraftComparison(r,["SELF_CARE"]);assert.equal(comparison.referenceMatchingDraftWithheld,true);assert.equal(comparison.clinicalCorrectness,"not_independently_adjudicated");const qualified=firstDraftComparison(r,null);assert.equal(qualified.firstReferenceAgreement,null);assert.equal(qualified.finalReferenceAgreement,null);});
test("runtime identity binds patient, prompt, graph, corpus and actual journal configuration",()=>{const r=run();r.status="review_required";const plan={promptHash:r.promptHash,graphVersion:"evidence-graph/v22",corpusHash:"b".repeat(64),config},start={runId:r.runId,inputHash:r.inputHash,promptHash:r.promptHash,config};assert.deepEqual(candidateIdentityFailures(plan,r,r.message,start),[]);assert.ok(candidateIdentityFailures(plan,r,r.message,{...start,config:{...config,judgeStyle:"concise"}}).includes("START_IDENTITY_UNBOUND"));assert.ok(candidateIdentityFailures({...plan,promptHash:"c".repeat(64)},r,r.message,start).includes("RUNTIME_IDENTITY_MISMATCH"));});
test("an allowed model in the wrong role is still identity drift",()=>{const r=run();r.agents![0].model=config.models.safety;const plan={promptHash:r.promptHash,graphVersion:"evidence-graph/v22",corpusHash:"b".repeat(64),config};assert.ok(candidateIdentityFailures(plan,r,r.message).includes("RUNTIME_MODEL_MISMATCH"));});
test("a complete answer without retained corpus-bound evidence cannot pass identity",()=>{const r=run(),plan={promptHash:r.promptHash,graphVersion:"evidence-graph/v22",corpusHash:"b".repeat(64),config};assert.ok(candidateIdentityFailures(plan,r,r.message).includes("RUNTIME_EVIDENCE_BINDING_MISSING"));});
test("explicit hash claim is single-use even when manifest and destination are copied",()=>{const directory=mkdtempSync(join(tmpdir(),"cohort-claim-test-")),path=join(directory,"manifest.json"),ledger=join(directory,"claims"),plan={fingerprint:"a".repeat(64),authorization:{cohortAllocationUSD:55}} as CohortPlan;assert.throws(()=>claimCohortPlan(path,join(directory,"one"),plan,"bad",ledger),/HASH_CLAIM/);claimCohortPlan(path,join(directory,"one"),plan,plan.fingerprint,ledger);assert.throws(()=>claimCohortPlan(join(directory,"copied-manifest.json"),join(directory,"two"),plan,plan.fingerprint,ledger),/EEXIST/);});
test("all50 remain planned when a start is unfinished, with reservation retained",()=>{const reference=JSON.parse(readFileSync("data/evaluation/physician-system-reference-v2.json","utf8"));const plan={cases:reference.cases.map((c:{id:string;message:string;inputHash:string})=>({id:c.id,message:c.message,inputHash:c.inputHash})),promptHash:"a".repeat(64),fingerprint:"b".repeat(64),reservation,interpretation:"development reference only"} as CohortPlan;const result=summarizeCohort(plan,[],1,"INTERRUPTED");assert.equal(result.planned,50);assert.equal(result.unfinishedStarted,1);assert.equal(result.unattempted.length,49);assert.equal(result.accountedUSD,reservation.perRunUSD);assert.equal(result.cohort.plannedReferenceDenominator,49);});
