import type { Guidance } from "../disposition/contract.ts";
// Migrated verbatim; no new passage verification or physician approval implied.
export const legacyNotes: Guidance[] = [
  { id: "aha-heart-attack", title: "AHA: Warning Signs of a Heart Attack", url: "https://www.heart.org/en/health-topics/heart-attack/warning-signs-of-a-heart-attack", section: "Don't delay — call 911 right away", reviewedAt: "2026-09-10", summary: "Heart-attack warning symptoms warrant calling 911 immediately, even without diagnostic certainty. Chest pressure, arm discomfort, breathlessness, sweating or nausea can be warning symptoms. An EMS team can begin treatment on arrival and arrange rapid transport; people arriving by ambulance may receive faster hospital treatment. These are reasons to call, not a personalized numerical risk estimate. Do not delay emergency action to collect more history or read a link." },
  { id: "idsa-dfi-2023", title: "IWGDF/IDSA: Diabetes-Related Foot Infections (2023)", url: "https://www.idsociety.org/practice-guideline/diabetic-foot-infections/", section: "Recommendations 1, 2, 7 and 18", reviewedAt: "2026-09-10", summary: "Assess diabetic foot infection clinically from local or systemic inflammation and grade severity. Consider admission for severe infection, or moderate infection with important comorbidity. Suspected osteomyelitis can require probe-to-bone, radiographs and inflammatory markers. Deep infection or severe ischaemia requires urgent surgical consultation. A message alone cannot establish depth, perfusion or severity." },
  { id: "nice-ng19", title: "NICE NG19: Diabetic foot problems", url: "https://www.nice.org.uk/guidance/ng19/resources/diabetic-foot-problems-prevention-and-management-pdf-1837279828933", section: "1.4.1–1.4.2", reviewedAt: "2026-09-10", summary: "Limb- or life-threatening diabetic foot problems require immediate acute-service referral. Other active diabetic foot problems require referral within one working day and triage within one further working day. These are referral targets, not a universal statement that every wound requires emergency admission. Project interpretation for a new inflamed diabetic foot wound with unassessed severity: arrange in-person assessment today; escalate immediately when limb/life threat is suspected." },
  { id: "afp-pleuritic-2017", title: "AFP: Pleuritic Chest Pain — Sorting Through the Differential Diagnosis (2017)", url: "https://www.aafp.org/afp/2017/0901/p306", section: "SORT recommendations; initial differential", reviewedAt: "2026-09-10", summary: "Unexplained pleuritic chest pain requires history and physical examination for serious causes; consider PE, myocardial infarction, pericarditis, aortic dissection, pneumonia and pneumothorax. Chest radiography is recommended for unexplained pleuritic pain. Use validated decision rules only with their required inputs. These evaluation recommendations are SORT C (consensus/usual practice), not high-certainty trial evidence. Project interpretation: arrange same-day in-person evaluation when a message cannot establish a benign cause; emergency action for emergency features." },
  { id: "nhs-breathlessness", title: "NHS: Shortness of breath", url: "https://www.nhs.uk/symptoms/shortness-of-breath/", section: "Emergency and urgent advice; reviewed January 2024", reviewedAt: "2026-09-10", summary: "Severe breathing difficulty, inability to speak, blue/grey skin or sudden confusion require immediate emergency help. For children, difficulty breathing, blue/grey skin, confusion or abnormal responsiveness require emergency help. More breathlessness than usual warrants urgent advice.", projectInterpretation: "UK guidance uses 999/111; this US demo uses 911. Same-day examination for progressive COPD breathlessness and the limits of missing/normal oximetry are project clinical reasoning, not claims made by this NHS page." },
  { id: "cdc-common-cold", title: "CDC: Manage Common Cold", url: "https://www.cdc.gov/common-cold/treatment/index.html", section: "Manage symptoms; when to seek medical care (March 2026)", reviewedAt: "2026-09-10", summary: "Mild cold symptoms commonly improve with rest and fluids; antibiotics do not treat viral colds. Trouble breathing, dehydration, persistent symptoms, or worsening chronic conditions warrant medical attention. People at increased risk from influenza or COVID-19 should contact a clinician promptly even with mild symptoms because early antiviral treatment may matter. Age, immune status and comorbidity are relevant unknowns; this note does not establish a diagnosis or personal risk estimate." },
  { id: "asa-stroke", title: "American Stroke Association: Stroke Symptoms", url: "https://www.stroke.org/en/about-stroke/stroke-symptoms", section: "B.E. F.A.S.T.; transient ischemic attack", reviewedAt: "2026-09-10", summary: "Sudden one-sided weakness, speech difficulty, vision or balance changes may indicate stroke. Call 911 immediately, including when symptoms resolve. A transient episode is not proof of safety. EMS can initiate assessment and transport; no numerical personal risk is provided in this note." },
  { id: "mayo-cranial-csf", title: "Mayo Clinic: Cranial CSF leak symptoms and causes", url: "https://www.mayoclinic.org/diseases-conditions/csf-leak/symptoms-causes/syc-20522246", section: "Cranial symptoms, causes and risk factors; June 2026", reviewedAt: "2026-09-10", summary: "Cranial CSF leaks may cause clear watery drainage from one side of the nose or ear and altered taste. Head injury and sinus surgery are possible causes; spontaneous leaks can occur without surgery or trauma. These features suggest a differential, not a diagnosis from text.", projectInterpretation: "Ask relevant surgical/trauma history and drainage character. New persistent unilateral watery drainage warrants in-person assessment; this source does not prescribe a universal response deadline." },
  { id: "cuh-pituitary-aftercare", title: "Cambridge University Hospitals: Pituitary surgery aftercare", url: "https://www.cuh.nhs.uk/patient-information/going-home-following-removal-of-a-pituitary-tumour/", section: "Seek advice if you notice; approved January 2026", reviewedAt: "2026-09-10", summary: "After pituitary surgery, clear nasal fluid or frequently swallowed fluid with a salty taste warrants advice. Excessive nasal bleeding, headache with fever and neck stiffness, or visual deterioration are other warning features. Ordinary mucus, crusting and blood clots may occur after the operation.", projectInterpretation: "For suspected postoperative leakage, contact the operating team now for prompt assessment, or the emergency department if unavailable. This is a project routing interpretation, not a universal 911 rule for every postoperative runny nose." },
  { id: "nhs-head-injury", title: "NHS: Head injury and concussion", url: "https://www.nhs.uk/conditions/head-injury-and-concussion/", section: "Call 999 after head injury; reviewed May 2025", reviewedAt: "2026-09-10", summary: "After head injury, clear fluid from the nose or ears, a head wound with something inside it, reduced consciousness, seizure, or new neurological difficulty require emergency help. Do not drive yourself to the emergency department after head injury.", projectInterpretation: "Use 911 in this US demo. A recent fall driving an object deep into the nose raises concern for penetrating head injury even when intracranial involvement cannot be established remotely." },
];
